# Generated by Django 3.2.5 on 2023-06-13 10:55

from django.db import migrations, models
import school.file_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(null=True, upload_to=school.file_upload.item_files_directory)),
                ('age', models.CharField(max_length=2)),
            ],
        ),
    ]
