# Generated by Django 3.2.5 on 2023-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20230613_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='unique_ref',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
