# Generated by Django 3.2.5 on 2023-06-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20230612_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.guardian'),
        ),
    ]
