# Generated by Django 3.2.5 on 2023-06-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.data'),
        ),
    ]
