# Generated by Django 3.2.5 on 2023-06-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_grade_no_of_students'),
        ('student', '0005_auto_20230613_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.grade'),
        ),
    ]
