# Generated by Django 3.2.5 on 2023-06-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('student', '0006_student_std_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.data'),
        ),
        migrations.AlterField(
            model_name='student',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.data'),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
