# Generated by Django 3.2.5 on 2023-06-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_data_unique_ref'),
        ('student', '0007_auto_20230613_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.data'),
        ),
    ]
