# Generated by Django 3.2.5 on 2023-06-20 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20230620_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
