# Generated by Django 3.2.5 on 2023-06-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_grade_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='No_of_students',
            field=models.IntegerField(default=0),
        ),
    ]
